name: EldenRingModTranslator Pyinstaller
on: [ push ]
jobs:
  Build:
    runs-on: windows-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install PyQt6
      
      - name: Pyninstaller
        run: |
          pyinstaller --onefile main.py
      
      - name: Create Artifact
        id: vars2
        run: |
          mkdir out
          cp ./dist/main.exe ./out/
          cp ./data ./out/
          cp ./Yabber131/ ./out/
          cp ./README.md ./out/
          cp ./config.json ./out/
        shell: bash
      
      - name: Upload Actions File
        uses: actions/upload-artifact@v1.0.0
        with:
          name: release
          path: ${{github.workspace}}/out
