name: EldenRingModTranslator Pyinstaller
on: [ push ]
jobs:
  Build:
    runs-on: windows-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install PyQt6
          pip install pyqtdarktheme

      - name: Pyninstaller
        run: |
          pyinstaller -w -F -i "app.ico" main_er.py
          pyinstaller -w -F -i "app.ico" main_ds3.py


      - name: Create Artifact
        id: vars2
        run: |
          mkdir out
          cp ./dist/main*.exe ./out/
          cp -r ./db ./out/
          cp -r ./Yabber131/ ./out/
          cp -r ./glossaries/ ./out/
          cp ./README.md ./out/
          cp ./config*.json ./out/
          cp ./更新日志.txt ./out/
          cp ./app.ico ./out/
        shell: bash

      - name: Upload Actions File
        uses: actions/upload-artifact@v1.0.0
        with:
          name: release
          path: ${{github.workspace}}/out
